### PR TITLE
Proposal: use `gen_server:cast/2` in `ldclient_event_server:add_event/3`

### PR DESCRIPTION
**Pull request by bceskavich**
**Requirements**

- [ ] I have added test coverage for new or changed functionality
- [x] I have followed the repository's [pull request submission guidelines](../blob/main/CONTRIBUTING.md#submitting-pull-requests)
- [ ] I have validated my changes against all supported platform versions

**Related issues**

We use LaunchDarkly extensively at Knock, where we use the Erlang SDK in our Elixir backend. We have recently encountered a bottleneck in the SDK in the `ldclient_event_server:add_event/3` path that we think can be solved with a relatively simple change.

**Describe the solution you've provided**

Right now, `ldclient_event_server:add_event/3` dispatches via `gen_server:call/2`. Since each `call/2` is a blocking operation that backs up to the calling process, this can become a bottleneck (e.g. spikes in concurrent invocations of `ldclient:variation/3`, where each process is blocked by the genserver). 

By using `gen_server:cast/2`, we can make this action completely deferred to the caller processes. The `cast/2` will always return `ok` immediately, with the server itself handling the message async as it processes thru its mailbox.

Since the existing `add_event/3` API returns the same response as a `cast/2`, the change is really as simple as updating the internals of the one module.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

### CODE REVIEW

**Comment by kinyoklion** [comment]
Hello @bceskavich,

Thank you for looking into it! Your change sounds reasonable. 

We will take a look.

_Filed internally as 192174_

Thank you,
Ryan

**Comment by whatyouhide** [comment]
@kinyoklion sorry for reviving this old conversation. I agree that `cast` here is not necessarily the correct choice (as it causes potential unbounded pressure). However, a single LD `gen_server` might not be ideal for high throughput situations. Have we considered "partitioning" or pooling a few `gen_server`s to distribute load?

**Comment by kinyoklion** [comment]
@whatyouhide The interface for the SDK should allow a client to do this and to structure it as is best for their application. In that you can create instances with different tags and those tags will have all their own instances of the various components of the SDK.

The default is to create one default tagged instance, but it isn't the only option.

**Comment by kinyoklion** [comment]
Multiple instances will be multiple connections to LD though, which is worth keeping in mind.

**Pull request closed without merging**
