### PR TITLE
Local filesystem monitor fix

### PR DESCRIPTION
**Pull request by matt-glover**
I recently integrated this library into an Elixir application and tried to setup the local file monitor for use in development with file polling. When I configured the monitor to poll the file for changes I noticed that within a few seconds of startup it would consistently crash. I traced it through and provided what, I think, resolves the issue. This appears to fix the problem in the Elixir application where I discovered it and also seems to pass the test I used to replicate it in this repo (before reverting that test).

I did not check against many platforms. I only tested it on a few Ubuntu 20 machines running Erlang 24.0 and 24.1. I also temporarily added test coverage but I reverted it in a later commit as noted in the "Additional context" section.

**Requirements**

- [x] I have added test coverage for new or changed functionality
- [X] I have followed the repository's [pull request submission guidelines](../blob/master/CONTRIBUTING.md#submitting-pull-requests)
- [ ] I have validated my changes against all supported platform versions

**Describe the solution you've provided**

Best I can tell when the file monitor does not detect changes it should return `ok` along with the unchanged state in the tuple because things are still flowing down a successful path from the poller's perspective. I believe the error return should only be used when the other file interaction code fails when attempting to read changes/update state.

So I think the `ok` match at the `load_files_if_modified` call site is probably correct up on line 85:
```erlang
{ok, NewState} = load_files_if_modified(FilePaths, State),
```

Conceivably that could be altered to accept `error` as well but I suspect it's better for this call to fail if `load_files` (when a file is actually modified) returns an error for any reason.

**Additional context**
When I enabled the file watcher polling in my Elixir repo and started the app I got output similar to the following within a few seconds of starting up:

```
[info]  Terminating, reason: {{:badmatch,
  {:error,
   %{
     file_allow_duplicate_keys: false,
     file_auto_update: true,
     file_info: %{
       'config/dev-feature-flags.yaml' => {{2021, 12, 13}, {10, 35, 40}}
     },
     file_paths: ['config/dev-feature-flags.yaml'],
     file_poll_interval: 1000,
     storage_tag: :default,
     timer_ref: {:interval, #Reference<0.759936776.185335809.101600>}
   }}},
 [
   {:ldclient_update_file_server, :handle_info, 2,
    [
      file: '/home/matt/code/my_repo/deps/ldclient/src/ldclient_update_file_server.erl',
      line: 85
    ]},
   {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 695]},
   {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 771]},
   {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}
 ]}; Pid none
 
[error] GenServer #PID<0.710.0> terminating
** (MatchError) no match of right hand side value: {:error, %{file_allow_duplicate_keys: false, file_auto_update: true, file_info: %{'config/dev-feature-flags.yaml' => {{2021, 12, 13}, {10, 35, 40}}}, file_paths: ['config/dev-feature-flags.yaml'], file_poll_interval: 1000, storage_tag: :default, timer_ref: {:interval, #Reference<0.759936776.185335809.101600>}}}
    (ldclient 1.3.1) /home/matt/code/my_repo/deps/ldclient/src/ldclient_update_file_server.erl:85: :ldclient_update_file_server.handle_info/2
    (stdlib 3.15.2) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15.2) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:poll}
State: %{file_allow_duplicate_keys: false, file_auto_update: true, file_info: %{'config/dev-feature-flags.yaml' => {{2021, 12, 13}, {10, 35, 40}}}, file_paths: ['config/dev-feature-flags.yaml'], file_poll_interval: 1000, storage_tag: :default, timer_ref: {:interval, #Reference<0.759936776.185335809.101600>}} 
```

I can suppress the failure by looping a local external process that constantly `touch`es the file to make it look updated every time the file watch poller fires off.

I replicated this error in the test suite by extending the time the file watcher test waits. This can be seen by checking out commit c408b1b and running the test suite. It produces essentially the same error (truncated because the actual output is a bit longer and duplicates a lot of the info/error stuff):
```
%%% ldclient_file_SUITE: .......
=INFO REPORT==== 21-Dec-2021::08:53:32.590991 ===
Terminating, reason: {{badmatch,
                       {error,
                        #{file_allow_duplicate_keys => false,
                          file_auto_update => true,
                          file_info =>
                           #{"tmpfile.json" => {{2021,12,21},{8,53,32}}},
                          file_paths => ["tmpfile.json"],
                          file_poll_interval => 500,
                          storage_tag => watch_files,
                          timer_ref =>
                           {interval,#Ref<0.3457577346.2333081601.147520>}}}},
                      [{ldclient_update_file_server,handle_info,2,
                        [{file,
                          "/home/matt/code/erlang-server-sdk/src/ldclient_update_file_server.erl"},
                         {line,85}]},
                       {gen_server,try_dispatch,4,
                        [{file,"gen_server.erl"},{line,695}]},
                       {gen_server,handle_msg,6,
                        [{file,"gen_server.erl"},{line,771}]},
                       {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,226}]}]}; Pid none

=ERROR REPORT==== 21-Dec-2021::08:53:32.592195 ===
** Generic server <0.1307.0> terminating 
** Last message in was {poll}
** When Server state == #{file_allow_duplicate_keys => false,
                          file_auto_update => true,
                          file_info =>
                              #{"tmpfile.json" => {{2021,12,21},{8,53,32}}},
                          file_paths => ["tmpfile.json"],
                          file_poll_interval => 500,
                          storage_tag => watch_files,
                          timer_ref =>
                              {interval,#Ref<0.3457577346.2333081601.147520>}}
** Reason for termination ==
** {{badmatch,
        {error,
            #{file_allow_duplicate_keys => false,file_auto_update => true,
              file_info => #{"tmpfile.json" => {{2021,12,21},{8,53,32}}},
              file_paths => ["tmpfile.json"],
              file_poll_interval => 500,storage_tag => watch_files,
              timer_ref => {interval,#Ref<0.3457577346.2333081601.147520>}}}},
    [{ldclient_update_file_server,handle_info,2,
         [{file,
              "/home/matt/code/erlang-server-sdk/src/ldclient_update_file_server.erl"},
          {line,85}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,695}]},
     {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,771}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}

=CRASH REPORT==== 21-Dec-2021::08:53:32.593867 ===
  crasher:
    initial call: ldclient_update_file_server:init/1
    pid: <0.1307.0>
    registered_name: []
    exception error: no match of right hand side value 
                     {error,
                         #{file_allow_duplicate_keys => false,
                           file_auto_update => true,
                           file_info =>
                               #{"tmpfile.json" => {{2021,12,21},{8,53,32}}},
                           file_paths => ["tmpfile.json"],
                           file_poll_interval => 500,
                           storage_tag => watch_files,
                           timer_ref =>
                               {interval,
                                   #Ref<0.3457577346.2333081601.147520>}}}
      in function  ldclient_update_file_server:handle_info/2 (/home/matt/code/erlang-server-sdk/src/ldclient_update_file_server.erl, line 85)
      in call from gen_server:try_dispatch/4 (gen_server.erl, line 695)
      in call from gen_server:handle_msg/6 (gen_server.erl, line 771)
    ancestors: [ldclient_instance_stream_watch_files,
                  ldclient_instance_watch_files,ldclient_sup,<0.1186.0>]
    message_queue_len: 0
    messages: []
    links: [<0.1295.0>,<0.769.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 17731
    stack_size: 29
    reductions: 2748
  neighbours:

=SUPERVISOR REPORT==== 21-Dec-2021::08:53:32.594055 ===
    supervisor: {local,ldclient_instance_stream_watch_files}
    errorContext: child_terminated
    reason: {{badmatch,
                 {error,
                     #{file_allow_duplicate_keys => false,
                       file_auto_update => true,
                       file_info =>
                           #{"tmpfile.json" => {{2021,12,21},{8,53,32}}},
                       file_paths => ["tmpfile.json"],
                       file_poll_interval => 500,storage_tag => watch_files,
                       timer_ref =>
                           {interval,#Ref<0.3457577346.2333081601.147520>}}}},
             [{ldclient_update_file_server,handle_info,2,
                  [{file,
                       "/home/matt/code/erlang-server-sdk/src/ldclient_update_file_server.erl"},
                   {line,85}]},
              {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,695}]},
              {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,771}]},
              {proc_lib,init_p_do_apply,3,
                  [{file,"proc_lib.erl"},{line,226}]}]}
    offender: [{pid,<0.1307.0>},
               {id,ldclient_update_file_server},
               {mfargs,{ldclient_update_file_server,start_link,[watch_files]}},
               {restart_type,permanent},
               {significant,false},
               {shutdown,5000},
               {child_type,worker}]
```

Unfortunately I'm not a strong Erlang developer at the moment so I opted to demo the issue in that test change commit (c408b1b) and then reverted it to avoid extending test runtimes. My suspicion is that the current test only passes because the file monitor test gen_server crashes and restarts during the test run picking up the file changes on restart. The test is rather quick so it doesn't fail/restart enough times to fully crash normally but the increased delay gives it enough time to fully fail and make the test fail.

### CODE REVIEW

**Comment by keelerm84** [comment]
Thank you for your contribution. We are going to need a little time before we are able to review this PR. We will provide an update once it has been reviewed.

**Comment by kinyoklion** [comment]
Hello @matt-glover,

Thank you for working through this! There are a couple things that I think could help with the testing.

I think first we could just change the polling interval from the very reasonable 500, down to something like 50 for the test. That way it will fail more than 10 times before that test checks the value.

The second would be to add:
```
-ifdef(TEST).
-compile(export_all).
-endif.
```

to `ldclient_update_file_server.erl`, then we could write a test like:
```
load_non_modified_file(_) ->
    {ok, State} = ldclient_update_file_server:init([default]),
    {ok, NewState} = ldclient_update_file_server:load_files_if_modified([code:priv_dir(ldclient) ++ "/flags-from-file.json"], State),
    {ok, NewState} = ldclient_update_file_server:load_files_if_modified([code:priv_dir(ldclient) ++ "/flags-from-file.json"], NewState).
```

This way we see that checking the same file twice will result in `ok` and also the state doesn't change.

**Comment by matt-glover** [comment]
Totally makes sense. I've updated / added tests as suggested.

I also temporarily (locally) reverted the app code change to verify that the tests fail as expected.

Also it was great to learn about the ability to conditionally export different functions for the test env in Erlang. Thanks for the suggestion!

**Comment by kinyoklion** [comment]
I've merged this into the `contrib` branch, and we can take it from there and get it in a release.
Thank you!

**Comment by kinyoklion** [comment]
Hello @matt-glover,

Version [1.3.2](https://github.com/launchdarkly/erlang-server-sdk/releases/tag/1.3.2) has been released and includes your fix.

Thank you!

**Pull request merged**
